version:   '3'
services:
	mysqlbd:
		build:
      dockerfile: ./docker/mysql.Dockerfile
      context:  .
		image:	rodrigotenorio86/mysql
		container_name:	bd_mysql
		ports:
			- "3306:3306"
		networks:
			- production-network
		environment:
			MYSQL_ROOT_PASSWORD: Rr123
	api-rest:
		build:
			dockerfile: ./docker/Dockerfile
			context:  .
		image:	rodrigotenorio86/api-rest-beer
		container_name:	api-rest
		ports:
			- "8080:9000"
		networks:
			- production-network
		depends_on:
			- "mysqldb"

networks:
	production-network:
		driver:	bridge
