version:  '3'
services:
  bd_mysql:
    image:  rodrigotenorio86/mysql
    container_name: bd_mysql
    ports:
      - "3306:3306"
    networks:
      - production-network
    environment:
      MYSQL_ROOT_PASSWORD: Rr123
      MYSQL_ROOT: root
      MYSQL_PASSWORD: Rr123
      MYSQL_DATABASE: beerhouse
  api-rest:
    image: rodrigotenorio86/api-rest-beer
    container_name: api-rest
    ports:
      - "8080:9000"
    networks:
      - production-network
    depends_on:
      - "bd_mysql"
networks:
  production-network:
    driver: bridge
